version: "3.9"
services:
  xray-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: javidi/xray-ui
    container_name: xray-ui
    restart: unless-stopped
    network_mode: host
    volumes:
      - $PWD/db/:/etc/xray-ui/
      - $PWD/cert/:/root/cert/
